### ISSUE TITLE
Error when adding item without tags

### ISSUE THREAD

**Issue by Strajk** [fniephaus/alfred-pocket#13]
Hi, thanks for great work!
Is it possible to add item without tags? It's not working for me... with any tag it's working fine.
![otsqil6qwa](https://cloud.githubusercontent.com/assets/697301/7120023/698ee1a8-e20a-11e4-8cf7-ae8526babdc4.gif)

**Comment by fniephaus** [comment]
Thanks for reporting, @Strajk.
I've pushed v4.6 which should resolve the issue.

**Comment by Strajk** [comment]
Thanks for quick feedback!
Can you pls also push it to Packal?

I still see 4.5 there
![pocket for alfred packal 2015-04-16 18-48-18](https://cloud.githubusercontent.com/assets/697301/7186333/2b557e5e-e469-11e4-8ad7-be284ec2e114.png)

**Comment by fniephaus** [comment]
Done :)

**Comment by Strajk** [comment]
Everything is awesomeeeee :)) thanks!

**Comment by fniephaus** [comment]
:smile:
